export default {
  uuid: 'a5ffaf71-7651-4c17-a397-b586b70e8691',
  valuesObj: {
    selected: false,
    id: 1234,
    start: new Date('2019-01-01T00:00:00.000Z'),
    finish: new Date('2019-01-03T00:00:00.000Z'),
    status: 'Готов',
    orderCardLink: 'Карточка 1234',
    payed: '',
    client: 'MY CLIENT',
    name: 'Ivanov',
    phone: '\'+380631234567',
    city: 'TestCity',
    contract: 'Клиент',
    category: 'Вторая (10 дней)',
    model: 'Tesla',
    delivery_prepaid: 150,
    summUah: '',
    summUsd: '300',
    prepaid: '100',
    oneTimeDiscount: '1000',
    paymentType: 'Отсрочка',
    manager: 'Sidorov',
    delivery_service: 'НП 111',
    delivery_incomingInvoice: '1234567890',
    delivery_outcomingInvoice: '',
    delivery_sendDate: '',
    master: 'Vano',
    masterCostOfWork: '250',
    commentPads: '',
    commentPlastic: 'This is a Sidorov`s comment for plastic',
    orderCardUrl: 'https://drive.google.com/file/d/orderCardUrl',
    connectors: 10,
    mount_custom: '',
    belt_zero: '',
    belt_single: '',
    belt_double: '',
    belt_pretensioner: '',
    belt_driver: '',
    belt_cleat: '',
    belt_live: '',
    belt_stripCustom: '',
    belt_minus: '',
    seat_small: '',
    seat_large: '',
    seat_custom: '',
    seat_headrest: '',
    seat_bag: '',
    curtains_small: '',
    curtains_large: '',
    curtains_largePlus: '',
    curtains_double: '',
    curtains_bag: 5,
    curtains_repair: '',
    curtains_dummy: '',
    wheel_single: 1,
    wheel_double: '',
    wheel_additional: '',
    wheel_cover: '',
    wheel_coverRef: '',
    wheel_coverRefSkin: '',
    wheel_coverCustom: '',
    wheel_byColor: '',
    wheel_byColorRef: '',
    wheel_logo: '',
    wheel_bag: '',
    wheel_minus: '',
    passenger_small: '',
    passenger_large: '',
    passenger_onlay1500: '',
    passenger_onlay2000: '',
    passenger_additional: '',
    passenger_bag: '',
    passenger_minus: '',
    knees_noPlastic: '',
    knees_small: '',
    knees_large: '',
    knees_smallFrame: '',
    knees_largeFrame: '',
    knees_byColor: '',
    knees_cover: '',
    knees_coverRef: '',
    knees_bag: '',
    knees_minus: '',
    roof_noHatch: '',
    roof_withHatch: '',
    roof_custom: '',
    block_simple: '',
    block_complex: '',
    block_custom: '',
    torpedo_standard: '',
    torpedo_custom: '',
    torpedo_onlayCustom: '',
  },
  formulasObj: {
    orderCardLink: '=ГИПЕРССЫЛКА("https://drive.google.com/drive/folders/orderCardLink";"Карточка 1234")',
  },
  notesObj: {
  },
};
